# Generated by Django 5.2.12 on 2026-03-10 17:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('games', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя автора')),
                ('channel_url', models.URLField(verbose_name='Ссылка на канал')),
                ('avatar', models.URLField(blank=True, null=True, verbose_name='Аватар')),
                ('subscribers_count', models.IntegerField(default=0, verbose_name='Подписчики')),
            ],
            options={
                'verbose_name': 'Автор',
                'verbose_name_plural': 'Авторы',
                'db_table': 'authors',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Название')),
                ('video_type', models.CharField(choices=[('guide', 'Гайд'), ('analysis', 'Разбор'), ('news', 'Новости'), ('stream', 'Стрим'), ('tip', 'Лайфхак')], max_length=20, verbose_name='Тип видео')),
                ('url', models.URLField(verbose_name='Ссылка на видео')),
                ('thumbnail', models.URLField(verbose_name='Превью')),
                ('duration', models.IntegerField(verbose_name='Длительность (сек)')),
                ('views_count', models.IntegerField(default=0, verbose_name='Просмотры')),
                ('likes_count', models.IntegerField(default=0, verbose_name='Лайки')),
                ('tags', models.JSONField(default=list, help_text='Теги для связи с игровыми сессиями', verbose_name='Теги')),
                ('uploaded_at', models.DateTimeField(verbose_name='Дата загрузки')),
                ('moderated', models.BooleanField(default=False, verbose_name='Промодерировано')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='videos.author', verbose_name='Автор')),
                ('game', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='games.game', verbose_name='Игра')),
                ('moderated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderated_videos', to=settings.AUTH_USER_MODEL, verbose_name='Модератор')),
            ],
            options={
                'verbose_name': 'Видео',
                'verbose_name_plural': 'Видео',
                'db_table': 'videos',
            },
        ),
        migrations.CreateModel(
            name='UserVideoInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watched_at', models.DateTimeField(auto_now_add=True, verbose_name='Время просмотра')),
                ('watch_duration', models.IntegerField(default=0, verbose_name='Длительность просмотра (сек)')),
                ('rating', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True, verbose_name='Оценка')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videos.video', verbose_name='Видео')),
            ],
            options={
                'verbose_name': 'Взаимодействие с видео',
                'verbose_name_plural': 'Взаимодействия с видео',
                'db_table': 'user_video_interactions',
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscribed_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата подписки')),
                ('unsubscribed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата отписки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscribers', to='videos.author', verbose_name='Автор')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Подписка',
                'verbose_name_plural': 'Подписки',
                'db_table': 'subscriptions',
                'unique_together': {('user', 'author')},
            },
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['game', 'video_type'], name='videos_game_id_be0495_idx'),
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['tags'], name='videos_tags_3d91e1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='uservideointeraction',
            unique_together={('user', 'video')},
        ),
    ]
