# Generated by Django 5.2.12 on 2026-03-10 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('genre', models.CharField(max_length=100, verbose_name='Жанр')),
                ('developer', models.CharField(max_length=200, verbose_name='Разработчик')),
                ('release_date', models.DateField(verbose_name='Дата релиза')),
                ('total_achievements', models.IntegerField(default=0, verbose_name='Всего достижений')),
                ('cover_image', models.URLField(blank=True, null=True, verbose_name='Обложка')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Игра',
                'verbose_name_plural': 'Игры',
                'db_table': 'games',
            },
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('type', models.CharField(choices=[('pc', 'ПК'), ('console', 'Консоль'), ('mobile', 'Мобильная')], max_length=20, verbose_name='Тип платформы')),
                ('specs', models.JSONField(blank=True, null=True, verbose_name='Технические характеристики')),
            ],
            options={
                'verbose_name': 'Платформа',
                'verbose_name_plural': 'Платформы',
                'db_table': 'platforms',
            },
        ),
        migrations.CreateModel(
            name='GamePlatform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.game')),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.platform')),
            ],
            options={
                'db_table': 'game_platforms',
                'unique_together': {('game', 'platform')},
            },
        ),
        migrations.AddField(
            model_name='game',
            name='platforms',
            field=models.ManyToManyField(related_name='games', through='games.GamePlatform', to='games.platform', verbose_name='Платформы'),
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['title'], name='games_title_d054a8_idx'),
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['genre'], name='games_genre_ac3a20_idx'),
        ),
    ]
