# Generated by Django 5.2.12 on 2026-03-25 14:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('games', '0001_initial'),
        ('videos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendation_type', models.CharField(choices=[('video', 'Видео'), ('game', 'Игра'), ('skill', 'Навык')], max_length=20, verbose_name='Тип рекомендации')),
                ('skill_tag', models.CharField(blank=True, max_length=50, null=True, verbose_name='Тег навыка')),
                ('score', models.FloatField(default=0.0, verbose_name='Оценка релевантности')),
                ('viewed', models.BooleanField(default=False, verbose_name='Просмотрено')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('game', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='games.game', verbose_name='Рекомендуемая игра')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('video', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='videos.video', verbose_name='Рекомендуемое видео')),
            ],
            options={
                'verbose_name': 'Рекомендация',
                'verbose_name_plural': 'Рекомендации',
                'db_table': 'recommendations',
                'ordering': ['-score', '-created_at'],
            },
        ),
    ]
